add zk mooc Series updates，including KZG and Lecture1
WTFAcademy/WTF-zk pull request #23
Opened 2024-02-22 03:15 UTC by miles-six

updates ZK Mooc Series

2024-02-22 05:58 UTC, flyq requested changes

2024-02-22 05:58 UTC, flyq commented on Zk Mooc Series/KZG.md
> +多项式 P(x)可以用系数表述,如$p(x)=6x^5+0x^4+0x^3+0x^2+0x^1-55$简单可表示为
```suggestion
多项式 $P(x)$ 可以用系数表述,如 $p(x)=6x^5+0x^4+0x^3+0x^2+0x^1-55$ 简单可表示为
```
P(x) 也用 latex 吧，前后统一，并且 $ 符号前后如果是字符需要留空格，不然无法识别为 latex，下同

2024-02-22 05:58 UTC, flyq commented on Zk Mooc Series/KZG.md
> +可进入 [https://ceremy.ethereum.org](https://ceremy.ethereum.org) 参与以太坊社区组织的 KZG Ceremony 的生成过程,成为其中一名贡献者!
```suggestion
可进入 [https://ceremony.ethereum.org](https://ceremony.ethereum.org/) 查看以太坊社区组织的 KZG Ceremony 的生成过程。
```

2024-02-22 05:58 UTC, flyq commented on Zk Mooc Series/KZG.md
> +KZG 承诺又叫做 KZG10 承诺,是由 Kate, Zaverucha, and Goldberg 三位作者共同提出.
需要统一为中文结尾用中文标点符号，英文结尾用英文标点符号。下同

2024-02-22 05:58 UTC, flyq commented on Zk Mooc Series/KZG.md
> +> P(X)=(X-m)*q(x)
```suggestion
> P(x)=(x-m)*q(x)
```
统一用 $x$ 吧，和前后文对应

2024-02-22 06:28 UTC, AmazingAng commented
感谢贡献，ppt截图最好能改成markdown公式，统一下格式。

2024-02-24 01:52 UTC, flyq approved these changes
lgtm

2024-02-27 02:18 UTC, AmazingAng approved these changes
Lgtm

2024-02-27 02:18 UTC, merged